name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore src/kube.sln -c Release -o ./bin/PublishOutput
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-restore --no-build src/kube.sln -c Release -o ./bin/PublishOutput
