name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet publish src/kube.sln -c Release

    - name: Test
      run: dotnet test src/kube.sln --verbosity normal

    - name: Build and push Docker image - kube-client
      uses: docker/build-push-action@v1.1.0
      with:
        path: src/KubeClient/bin/Release/netcoreapp3.0/
        repository: zamboch/kube-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true

    - name: Build and push Docker image - kube-gateway
      uses: docker/build-push-action@v1.1.0
      with:
        path: src/KubeGatewayHost/bin/Release/netcoreapp3.0/
        repository: zamboch/kube-gateway
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true

    - name: Build and push Docker image - kube-silo
      uses: docker/build-push-action@v1.1.0
      with:
        path: src/KubeSiloHost/bin/Release/netcoreapp3.0/
        repository: zamboch/kube-silo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
